### ISSUE TITLE
Add SoftPool in pytorch-pooling to the SPP module in YOLOv5

### ISSUE THREAD

**Issue by Leprechault** [rentainhe/pytorch-pooling#1]
Hi, 

I'd like to add SoftPool in `pytorch-pooling` and remove SPP module in my YOLO code:

```
class SPPF(nn.Module): 
     # Spatial Pyramid Pooling - Fast (SPPF) layer 
     def __init__(self, c1, c2, k=5):  # equivalent to SPP(k=(5, 9, 13)) 
         super().__init__() 
         c_ = c1 // 2  # hidden channels 
         self.cv1 = Conv(c1, c_, 1, 1) 
         self.cv2 = Conv(c_ * 4, c2, 1, 1) 
         self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2) 
  
     def forward(self, x): 
         x = self.cv1(x) 
         with warnings.catch_warnings(): 
             warnings.simplefilter('ignore')  # suppress torch 1.9.0 max_pool2d() warning 
             y1 = self.m(x) 
             y2 = self.m(y1) 
             return self.cv2(torch.cat((x, y1, y2, self.m(y2)), 1)) 
```

Please, where I find these changes in the `pytorch-pooling` code for this use.

Thanks in advance!

**Comment by rentainhe** [comment]
> Hi,
> 
> I'd like to add SoftPool in `pytorch-pooling` and remove SPP module in my YOLO code:
> 
> ```
> class SPPF(nn.Module): 
>      # Spatial Pyramid Pooling - Fast (SPPF) layer 
>      def __init__(self, c1, c2, k=5):  # equivalent to SPP(k=(5, 9, 13)) 
>          super().__init__() 
>          c_ = c1 // 2  # hidden channels 
>          self.cv1 = Conv(c1, c_, 1, 1) 
>          self.cv2 = Conv(c_ * 4, c2, 1, 1) 
>          self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2) 
>   
>      def forward(self, x): 
>          x = self.cv1(x) 
>          with warnings.catch_warnings(): 
>              warnings.simplefilter('ignore')  # suppress torch 1.9.0 max_pool2d() warning 
>              y1 = self.m(x) 
>              y2 = self.m(y1) 
>              return self.cv2(torch.cat((x, y1, y2, self.m(y2)), 1)) 
> ```
> 
> Please, where I find these changes in the `pytorch-pooling` code for this use.
> 
> Thanks in advance!

I think maybe you can directly replace `self.m` with `SoftPool`  using this code:
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.nn.modules.utils import _triple, _pair, _single

class SoftPool2d(nn.Module):
    def __init__(self, kernel_size, stride, padding=0):
        super(SoftPool2d,self).__init__()
        self.kernel_size = kernel_size
        self.stride = stride
        self.padding = padding

    def forward(self, x):
        x = self.soft_pool2d(x, kernel_size=self.kernel_size, stride=self.stride)
        return x

    def soft_pool2d(self, x, kernel_size=2, stride=None, force_inplace=False):
        kernel_size = _pair(kernel_size)
        if stride is None:
            stride = kernel_size
        else:
            stride = _pair(stride)
        _, c, h, w = x.size()
        e_x = torch.sum(torch.exp(x),dim=1,keepdim=True)
        return F.avg_pool2d(x.mul(e_x), kernel_size, stride=stride).mul_(sum(kernel_size)).div_(F.avg_pool2d(e_x, kernel_size, stride=stride).mul_(sum(kernel_size)))

def soft():
    print("You are using Soft Pooling Method")
    return SoftPool2d
```

**Comment by Leprechault** [comment]
> > Hi,
> > I'd like to add SoftPool in `pytorch-pooling` and remove SPP module in my YOLO code:
> > ```
> > class SPPF(nn.Module): 
> >      # Spatial Pyramid Pooling - Fast (SPPF) layer 
> >      def __init__(self, c1, c2, k=5):  # equivalent to SPP(k=(5, 9, 13)) 
> >          super().__init__() 
> >          c_ = c1 // 2  # hidden channels 
> >          self.cv1 = Conv(c1, c_, 1, 1) 
> >          self.cv2 = Conv(c_ * 4, c2, 1, 1) 
> >          self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2) 
> >   
> >      def forward(self, x): 
> >          x = self.cv1(x) 
> >          with warnings.catch_warnings(): 
> >              warnings.simplefilter('ignore')  # suppress torch 1.9.0 max_pool2d() warning 
> >              y1 = self.m(x) 
> >              y2 = self.m(y1) 
> >              return self.cv2(torch.cat((x, y1, y2, self.m(y2)), 1)) 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please, where I find these changes in the `pytorch-pooling` code for this use.
> > Thanks in advance!
> 
> I think maybe you can directly replace `self.m` with `SoftPool` using this code:
> 
> ```python
> import torch
> import torch.nn as nn
> import torch.nn.functional as F
> from torch.nn.modules.utils import _triple, _pair, _single
> 
> class SoftPool2d(nn.Module):
>     def __init__(self, kernel_size, stride, padding=0):
>         super(SoftPool2d,self).__init__()
>         self.kernel_size = kernel_size
>         self.stride = stride
>         self.padding = padding
> 
>     def forward(self, x):
>         x = self.soft_pool2d(x, kernel_size=self.kernel_size, stride=self.stride)
>         return x
> 
>     def soft_pool2d(self, x, kernel_size=2, stride=None, force_inplace=False):
>         kernel_size = _pair(kernel_size)
>         if stride is None:
>             stride = kernel_size
>         else:
>             stride = _pair(stride)
>         _, c, h, w = x.size()
>         e_x = torch.sum(torch.exp(x),dim=1,keepdim=True)
>         return F.avg_pool2d(x.mul(e_x), kernel_size, stride=stride).mul_(sum(kernel_size)).div_(F.avg_pool2d(e_x, kernel_size, stride=stride).mul_(sum(kernel_size)))
> 
> def soft():
>     print("You are using Soft Pooling Method")
>     return SoftPool2d
> ```

Thanks very much @rentainhe!! Problem solved!!

**Comment by rentainhe** [comment]
> > > Hi,
> > > I'd like to add SoftPool in `pytorch-pooling` and remove SPP module in my YOLO code:
> > > ```
> > > class SPPF(nn.Module): 
> > >      # Spatial Pyramid Pooling - Fast (SPPF) layer 
> > >      def __init__(self, c1, c2, k=5):  # equivalent to SPP(k=(5, 9, 13)) 
> > >          super().__init__() 
> > >          c_ = c1 // 2  # hidden channels 
> > >          self.cv1 = Conv(c1, c_, 1, 1) 
> > >          self.cv2 = Conv(c_ * 4, c2, 1, 1) 
> > >          self.m = nn.MaxPool2d(kernel_size=k, stride=1, padding=k // 2) 
> > >   
> > >      def forward(self, x): 
> > >          x = self.cv1(x) 
> > >          with warnings.catch_warnings(): 
> > >              warnings.simplefilter('ignore')  # suppress torch 1.9.0 max_pool2d() warning 
> > >              y1 = self.m(x) 
> > >              y2 = self.m(y1) 
> > >              return self.cv2(torch.cat((x, y1, y2, self.m(y2)), 1)) 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Please, where I find these changes in the `pytorch-pooling` code for this use.
> > > Thanks in advance!
> > 
> > 
> > I think maybe you can directly replace `self.m` with `SoftPool` using this code:
> > ```python
> > import torch
> > import torch.nn as nn
> > import torch.nn.functional as F
> > from torch.nn.modules.utils import _triple, _pair, _single
> > 
> > class SoftPool2d(nn.Module):
> >     def __init__(self, kernel_size, stride, padding=0):
> >         super(SoftPool2d,self).__init__()
> >         self.kernel_size = kernel_size
> >         self.stride = stride
> >         self.padding = padding
> > 
> >     def forward(self, x):
> >         x = self.soft_pool2d(x, kernel_size=self.kernel_size, stride=self.stride)
> >         return x
> > 
> >     def soft_pool2d(self, x, kernel_size=2, stride=None, force_inplace=False):
> >         kernel_size = _pair(kernel_size)
> >         if stride is None:
> >             stride = kernel_size
> >         else:
> >             stride = _pair(stride)
> >         _, c, h, w = x.size()
> >         e_x = torch.sum(torch.exp(x),dim=1,keepdim=True)
> >         return F.avg_pool2d(x.mul(e_x), kernel_size, stride=stride).mul_(sum(kernel_size)).div_(F.avg_pool2d(e_x, kernel_size, stride=stride).mul_(sum(kernel_size)))
> > 
> > def soft():
> >     print("You are using Soft Pooling Method")
> >     return SoftPool2d
> > ```
> 
> Thanks very much @rentainhe!! Problem solved!!


You're welcome~
